### ISSUE TITLE
GitHub action failing

### ISSUE THREAD

**Issue by wragge** [frictionlessdata/frictionless-ci#47]
# Overview

I use the Frictionless GitHub action in a number of repositories to check datasets created updated on a weekly schedule. Today the action failed to run, generating the same error in all repositories:

```
 exec /bin/sh: no such file or directory
  The command '/bin/sh -c curl -fsSL https://deb.nodesource.com/setup_14.x | bash - &&   apt-get install -y nodejs &&   npm install --production &&   pip install -r requirements.txt' returned a non-zero code: 1
```

My workflow file contains:

``` yaml
name: frictionless

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Fetch latest data"]
    types:
      - completed

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true # add this to download LFS files
          submodules: true # add this to download submodules
      - name: Validate data
        uses: frictionlessdata/repository@v1
```

I tried updating to `repository@v2` but that didn't help.
